// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSIEq--9CBANCtmKjcFqVZ8PNUamw7gmU',
    appId: '1:483796877712:android:e2c2c20ceaf93b3c03f315',
    messagingSenderId: '483796877712',
    projectId: 'mobile-app-d8647',
    storageBucket: 'mobile-app-d8647.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BQQ08us1U0WroauYsfscZYhY01MJz00',
    appId: '1:483796877712:web:3f457382bd4f259d03f315',
    messagingSenderId: '483796877712',
    projectId: 'mobile-app-d8647',
    authDomain: 'mobile-app-d8647.firebaseapp.com',
    storageBucket: 'mobile-app-d8647.firebasestorage.app',
    measurementId: 'G-JST6C2GXH0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWLuSLXAvOEXH6PyLKZ3jddPlp4mo8cc',
    appId: '1:483796877712:ios:0a1bcb7dab11f71303f315',
    messagingSenderId: '483796877712',
    projectId: 'mobile-app-d8647',
    storageBucket: 'mobile-app-d8647.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWLuSLXAvOEXH6PyLKZ3jddPlp4mo8cc',
    appId: '1:483796877712:ios:0a1bcb7dab11f71303f315',
    messagingSenderId: '483796877712',
    projectId: 'mobile-app-d8647',
    storageBucket: 'mobile-app-d8647.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7BQQ08us1U0WroauYsfscZYhY01MJz00',
    appId: '1:483796877712:web:203b0951e1a5a1b503f315',
    messagingSenderId: '483796877712',
    projectId: 'mobile-app-d8647',
    authDomain: 'mobile-app-d8647.firebaseapp.com',
    storageBucket: 'mobile-app-d8647.firebasestorage.app',
    measurementId: 'G-X3PTD3Z6ZP',
  );

}